services:
  api:
    build: .
    container_name: ical-api
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - START_TIMESTAMP=${START_TIMESTAMP}
      - END_TIMESTAMP=${END_TIMESTAMP}
      - SEPARATOR=${SEPARATOR}
    volumes:
      - api-secrets:/root/secret
      - /var/log:/root/log
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    networks:
      default:
        aliases:
          - api

  loki:
    image: grafana/loki:3.4
    container_name: ical-loki
    restart: unless-stopped
    ports:
      - "3100:3100"
    command:
      - "-config.file=/etc/loki/local-config.yaml"
    volumes:
      - ./loki-config.yml:/etc/loki/local-config.yaml
      - loki_data:/loki
    networks:
      default:
        aliases:
          - loki

  promtail:
    image: grafana/promtail:3.4
    container_name: ical-promtail
    restart: unless-stopped
    ports:
      - 9080:9080
    volumes:
      - /var/log:/var/log
      - ./promtail-config.yml:/etc/promtail/config.yml
    command:
      - "-config.file=/etc/promtail/config.yml"
    depends_on:
      - loki
    networks:
      default:
        aliases:
          - promtail

  prometheus:
    image: prom/prometheus:v3.2.0
    container_name: ical-prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
    ports:
      - 9090:9090
    networks:
      default:
        aliases:
          - prometheus

  grafana:
    image: grafana/grafana:latest
    container_name: ical-grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - loki
    networks:
      default:
        aliases:
          - grafana

volumes:
  api-secrets:
  prometheus_data:
  loki_data:
  grafana_data:
