{
 "title": "Logs",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "UpTime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "up", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_requests_total{path!=\"/metrics\", path!=\"/static/\"}[$__rate_interval])",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{job=\"varlogs\"} | json | __error__=``"
    }
   ]
  }
 ]
}